### ISSUE TITLE
how can i get  spend key and view key

### ISSUE THREAD

**Issue by zhp1254** [exantech/monero-fastsync#4]
spend = "28184c08eb7dd8d365af926dd4e2ed2685688c207e9d3f7a9e2d4d5dc8aaa64e"
view  = "1a7f0e754421317b633aabce2a98e41fa11afeb9c5be5037e727e51f3ef96600"

where can i get them

**Comment by naughtyfox** [comment]
Hi! 

Generally you can retrieve it from your `monero-wallet-cli` with `viewkey` and `spendkey` commands. But in fact you don't need it if you compile your wallet with this patch - https://github.com/exantech/monero/tree/patch-v0.13/fastsync.

Bear in mind this project is in beta test stage and hasn't been publicly announced yet.

Good luck! Looking forward for your feedback!
