### ISSUE TITLE
how do i create transaction without wallet rpc api

### ISSUE THREAD

**Issue by zhp1254** [exantech/monero-fastsync#5]
i generate spendkey 、viewkey 、address with moneroutil,     and i store the address utxo on my mysql database , the utxo is find on moneroblocks.info with my address
is that possible to create transaction without wallet rpc api
if it possible, how could i do it

**Comment by naughtyfox** [comment]
You can't assemble transaction with this service. This isn't it's been made for.

**Comment by zhp1254** [comment]
is it possible to decode outputs_data_hex(the outresult of wallet rpc export_outputs) by repo moneroutil

**Comment by naughtyfox** [comment]
The question seems irrelevant to current repo
