### ISSUE TITLE
[Question] Size of DB in relation to blockchain

### ISSUE THREAD

**Issue by Mansarde** [exantech/monero-fastsync#6]
First of all, this looks like a really interesting project!
Being able to re-sync a wallet quickly without having to scan the whole blockchain again sounds awesome.

Is the data stored in the fastsync DB about the same as a Monero LMDB would contain?
Or more to the point: Once synced, will the fastsync DB be about the same size as a Monero LMDB file?

**Comment by naughtyfox** [comment]
Hi!
> Is the data stored in the fastsync DB about the same as a Monero LMDB would contain?

We didn't test it on mainnet yet, so we have no estimation. But we will soon!

> Once synced, will the fastsync DB be about the same size as a Monero LMDB file?

More probably it's size may be even more

**Comment by Mansarde** [comment]
> More probably it's size may be even more

Kk, that makes sense, at least because you have to store the fastsync data for the wallets in addition to the blockchain data.
I just wasn't sure if the actual blockchain data itself was bigger.

> We didn't test it on mainnet yet, so we have no estimation. But we will soon!

That's good news, would've tried this myself yesterday, but unfortunately I'm short on space at the moment.^^

Anyways, a very awesome project, thx and keep up the good work.
Much appreciated! 👍

**Comment by naughtyfox** [comment]
@Mansarde 
We synced mainnet and it took about 60 GB

**Comment by Mansarde** [comment]
Oh wow, that's 10 GB less, nice!
Good job! :)
